version: '3'
services:
  apachephp:
    image: zilmar/php7-lamp
    container_name: apachephp
    ports:
      - "80:80"
    volumes:
      - ./webdata:/var/www/html
    networks:
      - lamp
    depends_on:
      - "mysql"
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: lamp
      MYSQL_USER: lamp
      MYSQL_PASSWORD: lamp
      MYSQL_DATABASE: lamp
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - lamp
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: lamp
      PMA_PASSWORD: lamp
    ports:
      - "8080:80"
    networks:
      - lamp
    depends_on:
      - "mysql"
networks:
  lamp:
    driver: bridge
